### PR TITLE
[#938] enable format string checking for clojure.tools.logging

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by celwell** [comment]
Just double-checking, is that `#_` supposed to be here: https://github.com/borkdude/clj-kondo/pull/941/files#diff-e1aaa64b205752f191f004233f9bd9beR1162

We are experiencing some false positives on this sort of thing:
`(format "/blah/%s/blah?query=Luke%%20Skywalker" s0)`

Kondo is saying I need 3 args not 2.

**Comment by borkdude** [comment]
Made an issue for it here which also describes the workaround of turning this linter off for now:

https://github.com/borkdude/clj-kondo/issues/944

Would appreciate it if you could list more false positives in the issue, so I can fix them.

**Comment by borkdude** [comment]
@celwell New version with a fix is released.

**Comment by celwell** [comment]
@borkdude Thanks for the quick fix, and for clj-kondo in general!

**Pull request merged**
