### PR TITLE
Add draft of flow diagram

### PR DESCRIPTION
**Pull request by sogaiu**
Here's a draft of a flow diagram that attempts to elaborate on:

> text -> code -> analysis -> linting

### CODE REVIEW

**Comment by borkdude** [comment]
Some additional information I wrote down on paper (sorry for my terrible writing):



I think it would be nice to reflect a nested flow in the diagram:

```
main -> core -> impl/core process-files -> impl/analyzer
                          sync-cache -> impl/cache
                          ...
             <- 
        core print
     <-
main exit code 0,1,2,3
```

**Comment by borkdude** [comment]
Maybe we could also take a look at:

“(Architecture) Diagrams as Data”
https://2019.clojure-conj.org/speaker-avi-flax/
https://youtu.be/HmHOYkTVxIg 

(just posted in Slack by Adam Feldman)

**Comment by sogaiu** [comment]
Intending to watch the talk :)

**Comment by sogaiu** [comment]
Here's some of the info from the notes:

```
main/main
  core/run!
    impl.core/process-files
      impl.core/process-file
        impl.analyzer/analyze-input
          impl.parser/parse-string
          impl.analyzer/analyze-expressions
    impl.core/index-defs-and-calls
    impl.core/sync-cache
    impl.linters/lint-var-usage
    impl.linters/lint-unused-namespaces!
    impl.linters/lint-unused-private-vars!
    impl.linters/lint-unused-bindings!
    impl.linters/lint-unresolved-symbols!
  core/print!
```

**Comment by sogaiu** [comment]
Perhaps it's worth mentioning somewhere the role and structure of ctx as the carrier and accumulator of information through the execution of most of the steps.

**Comment by sogaiu** [comment]
Another tool option is: https://github.com/jpmonettas/clograms

Steps to try out:

1. clj -Sdeps '{:deps {clograms {:mvn/version "RELEASE"}}}' -m clograms.server path-to-clj-kondo clj # replace path appropriately
2. wait for indexing to complete
3. observe url mentioned to open in browser
4. open url in browser
5. wait for loading
6. use search box at top left to identify something indexed (e.g. the function `run!`)
7. click to select found item -- this should cause a rectangle representing the item to appear in the main area below
8. repeat 6 and 7 to add more rectangles
9. drag from little squares that surround each rectangle to create arrows (connections?) to other squares on other rectangles
10. repeat as desired

clogram-clj-kondo-test

**Comment by borkdude** [comment]
I'll close this for now and will take another look once I'll work on the diagrams again.

**Pull request closed without merging**
