### PR TITLE
Add bound-fn to the analyzer

### LINKED ISSUE #688: unresolved-symbol on bound-fn arguments
**version**

`2019.12.14`

**platform**

JVM, invoking the API

**problem**

arguments defined for [bound-fn](https://clojuredocs.org/clojure.core/bound-fn) aren't linted properly

**repro**

provided this file on `src/test.clj`:
```clj
(ns test)

(bound-fn [arg]
   arg)
```

running clj-kondo provides the following output:
```clj
(clj-kondo.core/run! {:lint ["src/test.clj"]})
=>
{:findings [{:level :error,
             :type :unresolved-symbol,
             :filename "src/test.clj",
             :message "unresolved symbol arg",
             :row 3,
             :col 12}],
 :config {:skip-args [],
          :skip-comments false,
          :linters {:datalog-syntax {:level :error},
                    :redundant-do {:level :warning},
                    :type-mismatch {:level :error},
                    :redundant-let {:level :warning},
                    :misplaced-docstring {:level :warning},
                    :consistent-alias {:level :warning, :aliases {}},
                    :if {:level :warning},
                    :missing-test-assertion {:level :warning},
                    :use {:level :warning},
                    :unused-referred-var {:level :warning, :exclude {}},
                    :duplicate-set-key {:level :error},
                    :duplicate-map-key {:level :error},
                    :not-empty? {:level :warning},
                    :file {:level :error},
                    :refer-all {:level :warning},
                    :inline-def {:level :warning},
                    :unresolved-symbol {:level :error,
                                        :exclude [(user/defproject)
                                                  (clojure.test/are [thrown? thrown-with-msg?])
                                                  (cljs.test/are [thrown? thrown-with-msg?])
                                                  (clojure.test/is [thrown? thrown-with-msg?])
                                                  (cljs.test/is [thrown? thrown-with-msg?])]},
                    :cond-else {:level :warning},
                    :missing-docstring {:level :off},
                    :unused-import {:level :warning},
                    :deprecated-var {:level :warning},
                    :unbound-destructuring-default {:level :warning},
                    :syntax {:level :error},
                    :unused-namespace {:level :warning, :exclude []},
                    :private-call {:level :error},
                    :not-a-function {:level :error, :skip-args []},
                    :duplicate-require {:level :warning},
                    :unused-private-var {:level :warning},
                    :unresolved-namespace {:level :warning},
                    :invalid-arity {:level :error, :skip-args []},
                    :missing-map-value {:level :error},
                    :unreachable-code {:level :warning},
                    :redefined-var {:level :warning},
                    :unused-binding {:level :warning, :exclude-destructured-keys-in-fn-args false}},
          :lint-as {compojure.core/let-routes clojure.core/let,
                    cats.core/->>= clojure.core/->>,
                    clojure.core.async/go-loop clojure.core/loop,
                    rewrite-clj.custom-zipper.core/defn-switchable clojure.core/defn,
                    cljs.core.async.macros/go-loop clojure.core/loop,
                    clojure.test.check.generators/let clojure.core/let,
                    cats.core/->= clojure.core/->,
                    cljs.core.async/go-loop clojure.core/loop,
                    compojure.core/defroutes clojure.core/def,
                    schema.core/defschema clojure.core/def},
          :output {:format :text,
                   :summary true,
                   :analysis false,
                   :progress false,
                   :include-files [],
                   :exclude-files [],
                   :canonical-paths false}},
 :summary {:error 1, :warning 0, :info 0, :type :summary, :duration 13}}
```

My current workaround is adding `:lint-as {clojure.core/bound-fn clojure.core/fn}`

**expected behavior**

no errors at all.

I'm happy to look into a PR;

### PR DESCRIPTION
**Pull request by thumbnail**
fixes #688

QA'd locally by installing this branch and testing the repro provided in the issue 👍

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks. Can you also add a unit test for this to make sure that when we change something, a test will fail?

**Comment by borkdude** [comment]
@thumbnail 

The test you added is relevant to https://github.com/borkdude/clj-kondo/tree/master/analysis.
The added test is good, but I was thinking more of adding something to main_test, e.g. here:

chttps://github.com/borkdude/clj-kondo/blob/fe3421285321c4ec152219bfeded847c3e5b1388/test/clj_kondo/main_test.clj#L1768

Just add one example and test that it doesn't give any errors for bound-fn.

**Comment by borkdude** [comment]
Thanks!

**Comment by thumbnail** [comment]
yw :) thanks for the pointers

**Pull request merged**
