### PR TITLE
Add support for customizing exclusions to :refer :all

### PR DESCRIPTION
**Pull request by technomancy**
As discussed previously, this should take care of #560 and #681.

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks! 

Two things:

- Can you remove the rule for `clojure.test`? I want people to decide this for themselves and not make any decisions about specific namespaces.
- Can you add a unit test for the exclusions?

If you want me to take it over from here, that's ok too!

**Comment by technomancy** [comment]
> Can you remove the rule for clojure.test

I really don't think this is a good idea since that case is the whole reason why `:refer/all` exists, but if that's the only way this patch is going to get applied, then I can do it.

**Comment by borkdude** [comment]
Linters can be turned off (`{:linters {:refer-all {:level :off}}}`) and with this new configuration people can `:exclude [clojure.test]`. I think that gives people enough space to make their own decisions if they don't agree with the defaults. 

Small detail: `:refer :all` doesn't work with CLJS, so also not with `cljs.test`.

So yeah, I really insist removing it.

**Comment by yuhan0** [comment]
Just curious, what specifically about clojure.test needs a `:refer :all`? I use it like this in all my test namespaces:

```clojure
(ns something.test
  (:require [clojure.test :as t :refer [deftest testing is are]]))
```

which satisfies clj-kondo and doesn't cause any inconvenience.

**Comment by technomancy** [comment]
Oh, I see; that's a shame about CLJS; I haven't used it so I didn't know.

> Just curious, what specifically about clojure.test needs a :refer :all

The problem with the snippet above is that most test namespaces don't use `are`, and many of them don't use `testing`. So the snippet above will not lint anyway, it will trigger an unused refer warning. If I make a change to the test to add or remove a `testing` block, it's very tedious to have to make sure that the `ns` block changes as well even though I haven't changed what I'm requiring. That kind of tedium usually makes people want to just quit using the linter altogether.

**Comment by yuhan0** [comment]
That's an interesting perspective - personally I tend to disregard "unused refer" warnings as being harmless, so having a standardized set of refers (which my editor auto-inserts in newly created test ns) doesn't bother me enough to have to prune them.

I recall from using Python that the linter (probably pylint) would actually flag all unused refers in a wildcard import statement `from module import *`, so you would get dozens of warnings for all the vars being brought into scope and never used. 
Not saying that's what clj-kondo should do as well, but I think part of the rationale was to discourage people from using that syntax and be more explicit about what they were importing.

**Comment by borkdude** [comment]
Like @yuhan0, my default `clojure.test` libspec looks like:

```
(ns something.test
  (:require [clojure.test :as t :refer [deftest is testing]]))
```

without `are` since I almost never use it.

> That kind of tedium usually makes people want to just quit using the linter altogether.

That's an opinion. Opinions can be configured in `.clj-kondo/config.edn`. Personally I don't find it tedious.

**Comment by borkdude** [comment]
Like @yuhan0, my default clojure.test libspec looks like:

```
(ns something.test
  (:require [clojure.test :as t :refer [deftest is testing]]))
without are since I almost never use it.
```

> That kind of tedium usually makes people want to just quit using the linter altogether.

That's an opinion. Opinions can be configured in .clj-kondo/config.edn. Personally I don't find it tedious. Since the start of this linting rule you're the first one who wants this rule to be different for clojure.test. And now we have a config for it.

**Comment by MnRac** [comment]
Personally I believe the linter really shouldn't have any opinion on which namespaces should be ignored and that should be left down to user preference. Especially considering there's people that would use it both ways.

**Comment by borkdude** [comment]
Since I want to make a release one of these days, I'll merge this and make these changes:

-  Remove the specific setting for `clojure.test`
- Add a unit test for the new `:exclude` functionality

unless you will beat me to it.

**Comment by technomancy** [comment]
I won't be able to do it in the next few days; go for it. Thanks.

**Pull request merged**
