### PR TITLE
added securaties to diagnostic-languageserver.linters

### PR DESCRIPTION
**Pull request by sittim**
Helps with knowing if it is an error or just a warning.

### CODE REVIEW

**Comment by borkdude** [comment]
@sittim Can you explain what this config does? clj-kondo does not have level "note"?

**Comment by sittim** [comment]
This is a change for instruction in the `editor-integration.md` file.  The previous `diagnostic-languageserver.linters` configuration did not distinguish between error and warning.  The new configuration example adds the `"securaties"` key that instructs the *diagnostic-languageserver* to know if clj_kondo is outputting error or warning.

**Comment by borkdude** [comment]
Thank you.

**Comment by sittim** [comment]
Oh, also, I see what you are saying about the **note**, that was the copy and paste carry-over from https://github.com/iamcco/diagnostic-languageserver .  I agree that it would be cleaner to remove the line.

**Comment by borkdude** [comment]
@sittim Another PR is welcome for that.

**Pull request merged**
